### ISSUE TITLE
The latest version published on NPM doesn't run

### ISSUE THREAD

**Issue by matmunn** [VoxaAI/voxa-cli#36]
It looks like the version of this package that is currently published to npm (2.0.1) doesn't run since it's looking for `builder.js` which seems to have been deleted in 7059e0c1a399a8972a5d8d221321fbddf4aa00e2, without having the reference to it in `index.js`(https://github.com/VoxaAI/voxa-cli/blob/2.0.1/index.js#L10) updated.

**Comment by rmberrios** [comment]
@matmunn I released a new version (2.1.0) make sure to specify the spreadsheet URL instead of the id.


interaction.json
```
{
  "platforms": ["dialogflow", "alexa"],
  "spreadsheets": [
    "https://docs.google.com/spreadsheets/d/XXXXYYYYYZZZ/edit"
  ],
  "viewsPath": "out/google-sheet/",
  "speechPath": "out/google-sheet/speech-assets",
  "contentPath": "out/google-sheet/content",
  "assets": ["1MMjLUHViqoZTHXlMPU93Ig-Y0Gkyt5ey"],
  "assetsPath": "out/google-sheet/assets"
}

```

**Comment by rmberrios** [comment]
We want to specify other sources like Airtable, Office 365. That's why we now need to know the source of the spreadsheet in this case `google spreadheet`

**Comment by matmunn** [comment]
The new version (2.1.0) still references  builder.js in index.js and this file still does not exiset

**Comment by rmberrios** [comment]
@matmunn Could you try npx ask-cli interaction, Probably we will need to update the docs about it

**Comment by armonge** [comment]
actually, `npx voxa interaction`

**Comment by rmberrios** [comment]
I think this is solved. I'll close this issue.

**Comment by matmunn** [comment]
The docs are still incorrect

**Comment by matmunn** [comment]
Also `npx voxa interaction` results in `Command not found`

**Comment by matmunn** [comment]
Running `npx voxa-cli interaction` results in an uncaught promise:
```
 $ npx voxa-cli interaction
npx: installed 213 in 9.978s
timeframe: 2136.128ms
(node:5637) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at sanitizeView (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/src/Processor.ts:66:8)
    at _.chain.reduce (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/src/Processor.ts:96:21)
    at arrayReduce (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/node_modules/lodash/lodash.js:683:21)
    at Function.reduce (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/node_modules/lodash/lodash.js:9683:14)
    at /Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/node_modules/lodash/lodash.js:4374:28
    at arrayReduce (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/node_modules/lodash/lodash.js:4373:14)
    at LodashWrapper.wrapperValue (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/node_modules/lodash/lodash.js:9052:14)
    at voxaSheetsViews.map (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/src/Processor.ts:107:8)
    at Array.map (<anonymous>)
    at Object.viewsProcessor (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/src/Processor.ts:77:26)
    at new Schema (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/src/Schema.ts:42:18)
    at new DialogflowSchema (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/src/DialogflowSchema.ts:56:5)
    at Object.<anonymous> (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/src/InteractionBuilder.ts:109:20)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mat/.npm/_npx/5637/lib/node_modules/voxa-cli/lib/src/InteractionBuilder.js:4:58)
(node:5637) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5637) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It doesn't seem like `IVoxaSheet.data` is checking if it has a `value` property defined before running it through the `sanitizeView` function.
